/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom5.ui;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.TableColumnModelListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import nhom5.model.*;
import nhom5.util.ClonedNhanVien;
import nhom5.util.ClonedSanPham;
import nhom5.util.TienIch;
/**
 *
 * @author krayz
 */
public class HoaDonUI extends javax.swing.JDialog {
    
    private NhanVienBanHang nv;
    private String maHoaDon;
    private ArrayList<SanPham> dsSP;
    public boolean returnState;
    DefaultTableModel dtm;
    /**
     * Creates new form HoaDonUI
     */
    
    // Tao cua so hoa don tai buoc thanh toan
    
    public HoaDonUI(java.awt.Frame parent, String title, boolean modal, NhanVienBanHang nv, ArrayList<SanPham> dsSP) {
        super(parent, title, modal);
        this.dsSP = dsSP;
        this.nv = nv;
        this.maHoaDon = TienIch.sinhMaHD();
        this.returnState = false;
        
        initComponents();
        this.dtm = (DefaultTableModel) tbl.getModel();
        setInfomation();
        initTable();
        capNhatThanhTien();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        lblKhachGui = new javax.swing.JLabel();
        txtKhachGui = new javax.swing.JTextField();
        lblTraLai = new javax.swing.JLabel();
        txtTraLai = new javax.swing.JTextField();
        btnIn = new javax.swing.JButton();
        btnBoChon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tong tien");

        txtTongTien.setEditable(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        lblKhachGui.setText("Khach gui");

        txtKhachGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachGuiActionPerformed(evt);
            }
        });

        lblTraLai.setText("Tra lai");

        txtTraLai.setEditable(false);
        txtTraLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraLaiActionPerformed(evt);
            }
        });

        btnIn.setText("In hoa don");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnBoChon.setText("Bo chon");
        btnBoChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoChonActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã hóa đơn: ");

        jLabel6.setText("Nhân viên thu ngân: ");

        lblHoaDon.setText("null");

        lblNhanVien.setText("null");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "Mã", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 395, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTraLai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKhachGui, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBoChon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTraLai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKhachGui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(64, 64, 64)
                                .addComponent(lblHoaDon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNhanVien)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKhachGui, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKhachGui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTraLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBoChon)
                    .addComponent(btnIn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMess(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    private void initTable(){
        
        dtm.setRowCount(0);
        
        for(SanPham sp : dsSP){
            
            Object [] rowData = {sp.getTen(),sp.getMa(),0,sp.getGiaBan(),0};
            dtm.addRow(rowData);
            
        }
    }
    
    private int tinhTongTien() {
        int tongTien = 0;
        for(int i = 0; i < dtm.getRowCount(); i++) {
                tongTien += (Integer) tbl.getValueAt(i,2) * (Integer) tbl.getValueAt(i,3);
        }
        return tongTien;
    }
    private void setInfomation(){
        lblNhanVien.setText(nv.getTen()+"("+nv.getMa()+")"); 
        lblHoaDon.setText(this.maHoaDon);
    }
    private void capNhatThanhTien(){
        
        dtm.addTableModelListener(new TableModelListener(){
          @Override
            public void tableChanged(TableModelEvent e) {
                
                if(e.getType() == TableModelEvent.UPDATE) {

                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    if(column == 2) {

                        String maSP = tbl.getValueAt(row, 1).toString();
                        int soLuong = (Integer) tbl.getValueAt(row, column);

                        if(CuaHang.getDsSanPham().get(maSP).getSoLuong() < soLuong) {
                                sendMess("Khong du san pham");
                                tbl.setValueAt(0, row, column);
                                tbl.setValueAt(0, row, 4);
                                return;
                        }

                        else {
                                tbl.setValueAt((Integer) tbl.getValueAt(row,2) * (Integer) tbl.getValueAt(row,3), row, 4);
                        }

                        txtTongTien.setText(tinhTongTien()+"");
                        
                    }				
                }
            }  
        });
    }
    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void btnBoChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoChonActionPerformed
        int row = tbl.getSelectedRow();
        if(row != -1) {
            dtm.removeRow(row);
        }
    }//GEN-LAST:event_btnBoChonActionPerformed

    private void txtTraLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraLaiActionPerformed

    private void txtKhachGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachGuiActionPerformed
        try {
            int khachGui = Integer.parseInt(txtKhachGui.getText());
            int tongTien = Integer.parseInt(txtTongTien.getText());
            if(khachGui < tongTien) {
                sendMess("really?");
                return;
            }
            txtTraLai.setText((khachGui-tongTien)+"");
        }
        catch (Exception e1) {
                sendMess("Du lieu khong hop le");
                txtKhachGui.setText("0");
        }
    }//GEN-LAST:event_txtKhachGuiActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        
        if(dtm.getRowCount() > 0) {
           try{
            
            // Kiem tra cac o text

            if(txtKhachGui.getText().isEmpty()) {
                sendMess("Yeu cau nhap du thong tin cho hoa don");
            }
            
            else if(Integer.parseInt(txtKhachGui.getText()) - Integer.parseInt(txtTongTien.getText()) >= 0){

                HoaDon hd = new HoaDon(maHoaDon, new Date(), nv);
                
                // Cap nhat so luong san pham  
                
                for(int i = 0; i < dtm.getRowCount(); i++) {
                    String maSP = tbl.getValueAt(i, 1)+"";
                    SanPham sp = CuaHang.getDsSanPham().get(maSP);
                    int soLuongBan = (Integer)tbl.getValueAt(i,2);
                    
                    ClonedSanPham clone = new ClonedSanPham(sp, soLuongBan);
                    hd.themSanPham(clone);
                    
                    sp.setSoLuong(sp.getSoLuong()- soLuongBan);
                }

                // Them hoa don vao csdl

                QuanLy.themHoaDon(hd);

                // Thong bao thanh cong

                sendMess("In hoa don thanh cong!");
                returnState = true;
            }
           }
           catch(NumberFormatException e){
               sendMess("Du lieu dau vao khong hop le");
           }
        }
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonUI dialog = new HoaDonUI(new javax.swing.JFrame(),null,false,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoChon;
    private javax.swing.JButton btnIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblKhachGui;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblTraLai;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtKhachGui;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTraLai;
    // End of variables declaration//GEN-END:variables
}
