/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom5.ui;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import nhom5.model.CuaHang;
import nhom5.model.HoaDon;
import nhom5.model.NhanVienBanHang;
import nhom5.model.QuanLy;
import nhom5.model.SanPham;
import nhom5.tuongtacfile.PhienHoatDong;
import nhom5.util.TienIch;

/**
 *
 * @author Hoai Nguyen
 */
public class NhanVienUI extends javax.swing.JFrame {

    
    protected NhanVienBanHang nhanVien;
    protected HashMap<SanPham,Integer> dsSanPham; // Khoa la san pham, gia tri la so luong ban
    protected int tongTien; 
    private DefaultTableModel dtm;
   
    /**
     * Creates new form NhanVienUI
     */
    
    public NhanVienUI() {
        initComponents();
    }

    public NhanVienUI (String title, NhanVienBanHang nv){
            
        super(title);
        this.nhanVien= nv;
        this.dsSanPham = new HashMap<>();
        this.tongTien = 0;
        initComponents();
        getTableModel();
        showWindow();
        capNhatSoLuong();
        
    }
    
    private void sendMess(String message) {
        JOptionPane.showMessageDialog(null, message);
    }
    
    private void showWindow(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void getTableModel(){
        dtm = (DefaultTableModel)tbl.getModel();
        dtm.setRowCount(0);
    }
    
    private void clearTexts(){
        txtTimKiem.setText("");
        txtKhachGui.setText("");
        txtTraLai.setText("");
        txtTongTien.setText("");
    }
    
    private void capNhatSoLuong(){
        
        dtm.addTableModelListener(new TableModelListener(){
         
          @Override
            public void tableChanged(TableModelEvent e) {
                
                if(e.getType() == TableModelEvent.UPDATE) {

                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    if(column == 4){
                        String maSP = tbl.getValueAt(row, 0).toString();
                        SanPham sp = CuaHang.getDsSanPham().get(maSP);
                        int soLuong = (Integer) tbl.getValueAt(row, column);

                        if(sp.getSoLuong() < soLuong) {
                                sendMess("Khong du san pham");
                                tbl.setValueAt(1, row, column);
                                tbl.setValueAt(1, row, 5);
                                tongTien -= (dsSanPham.get(sp)-1)*sp.getGiaBan();
                                dsSanPham.replace(sp, 1);                            
                        }

                        else {
                            tongTien += (soLuong - dsSanPham.get(sp))*sp.getGiaBan();
                            dsSanPham.replace(sp, soLuong);
                            tbl.setValueAt((Integer) soLuong * sp.getGiaBan(), row, 5);
                        }

                        txtTongTien.setText(tongTien+"");    
                    }       				
                }
            }  
        });
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtTongTien = new javax.swing.JTextField();
        txtKhachGui = new javax.swing.JTextField();
        txtTraLai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBoChon = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        mnuDoiMatKhau = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Chọn");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Giá bán", "Còn lại", "Số lượng", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbl.getColumnModel().getColumn(4).setPreferredWidth(30);
            tbl.getColumnModel().getColumn(5).setResizable(false);
        }

        txtTongTien.setEditable(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        txtKhachGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachGuiActionPerformed(evt);
            }
        });

        txtTraLai.setEditable(false);

        jLabel1.setText("Nhập mã sản phẩm:");

        jLabel2.setText("Tổng tiền: ");

        jLabel3.setText("Khách trả: ");

        jLabel4.setText("Trả lại: ");

        btnBoChon.setText("Bỏ chọn");
        btnBoChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoChonActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Giao dịch mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jMenu1.setText("Tài khoản");

        mnuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDangXuat);

        mnuDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuDoiMatKhau.setText("Đổi mật khẩu");
        mnuDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDoiMatKhau);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTraLai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txtKhachGui, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLamMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnBoChon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThanhToan)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhachGui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnBoChon)
                    .addComponent(btnLamMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed

        nhanVien.dangXuat();
        
	LogInUI tmp = new LogInUI("Đăng nhập");
	
        dispose();
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoiMatKhauActionPerformed
    
        ChangePwdUI tmp = new ChangePwdUI(this,"Đổi mật khẩu",true,nhanVien);
        
    }//GEN-LAST:event_mnuDoiMatKhauActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        String maSanPham = txtTimKiem.getText();
        
        if(CuaHang.getDsSanPham().containsKey(maSanPham)) {
                
                SanPham sp = CuaHang.getDsSanPham().get(maSanPham);
                
                if(sp.getSoLuong() == 0){
                    sendMess("Het hang!");
                    return;
                }
                
                Object [] rowData = {sp.getMa(),sp.getTen(),sp.getGiaBan(),
                                     sp.getSoLuong(),1,sp.getGiaBan()};
                dtm.addRow(rowData);
                dsSanPham.put(sp, 1);
                tongTien += sp.getGiaBan();
        }
        
        else {
            sendMess("Ma san pham khong dung");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
     
        if(dtm.getRowCount() > 0 && tbl.getCellEditor() == null) {

            HoaDon hoaDon = nhanVien.thanhToan(dsSanPham);
            QuanLy.themHoaDon(hoaDon);
            
            dsSanPham.clear();
            tongTien = 0;
            
            clearTexts();
            dtm.setRowCount(0);
            
            sendMess("Thanh toan thanh cong!");
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void tblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblPropertyChange
         // TODO add your handling code here:
    }//GEN-LAST:event_tblPropertyChange

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtKhachGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachGuiActionPerformed
         try {
            
            int khachGui = Integer.parseInt(txtKhachGui.getText());
            int tongTien = Integer.parseInt(txtTongTien.getText());
            
            if(khachGui < tongTien) {
                sendMess("So tien khach tra nho hon tong gia tri don hang");
                return;
            }
            txtTraLai.setText((khachGui-tongTien)+"");
        }
         
        catch (Exception e1) {
                sendMess("Du lieu khong hop le");
                txtKhachGui.setText("0");
        }
    }//GEN-LAST:event_txtKhachGuiActionPerformed

    private void btnBoChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoChonActionPerformed
        
        int row = tbl.getSelectedRow();
        if(row != -1){
            
            String ma = (String) tbl.getValueAt(row, 0);
            SanPham sp = CuaHang.getDsSanPham().get(ma);
            
            tongTien -= dsSanPham.get(sp) * sp.getGiaBan();
            dsSanPham.remove(sp);
            
            dtm.removeRow(row);
        }
    }//GEN-LAST:event_btnBoChonActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
       tongTien = 0;
       dsSanPham.clear();
       clearTexts();
       dtm.setRowCount(0); 
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, 
            "Ban co chac muon thoat chuong trinh?", "Thoat", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
		
            PhienHoatDong.ketThuc();
      	}
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoChon;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtKhachGui;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTraLai;
    // End of variables declaration//GEN-END:variables
}
