/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom5.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nhom5.model.DiaPhim;
import nhom5.model.QuanLy;
import nhom5.util.TienIch;

/**
 *
 * @author Hoai Nguyen
 */
public class ThemDiaPhimUI extends javax.swing.JDialog {

    public boolean returnState;

    /**
     * Creates new form ThemDiaPhimUI
     */
    public ThemDiaPhimUI() {
        initComponents();
    }

    public ThemDiaPhimUI(JFrame parent, String title, boolean modal) {
        super(parent, title, modal);
        returnState = false;
        initComponents();
        setMa();
        showWindow();
    }

    private void sendMess(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    private void setMa() {
        txtMaSanPhamP.setText(TienIch.sinhMaSP("dp"));
    }

    private void showWindow() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaSanPhamP = new javax.swing.JTextField();
        txtMaSanPhamP.setEditable(false);
        jLabel2 = new javax.swing.JLabel();
        txtTenSanPhamP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDaoDien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTheLoaiP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGiaMuaP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiaBanP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuongP = new javax.swing.JTextField();
        btnThemP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã sản phẩm:");

        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setText("Đạo diễn:");

        jLabel4.setText("Thể loại:");

        jLabel5.setText("Giá mua:");

        jLabel6.setText("Giá bán:");

        jLabel7.setText("Số lượng:");

        btnThemP.setText("Thêm");
        btnThemP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSanPhamP, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtTenSanPhamP)
                            .addComponent(txtDaoDien)
                            .addComponent(txtTheLoaiP)
                            .addComponent(txtGiaMuaP)
                            .addComponent(txtGiaBanP)
                            .addComponent(txtSoLuongP)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnThemP)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSanPhamP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSanPhamP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDaoDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTheLoaiP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaMuaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaBanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoLuongP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnThemP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPActionPerformed
        // TODO add your handling code here:
        if (txtMaSanPhamP.getText().isEmpty()
                || txtTenSanPhamP.getText().isEmpty()
                || txtDaoDien.getText().isEmpty()
                || txtTheLoaiP.getText().isEmpty()
                || txtGiaMuaP.getText().isEmpty()
                || txtGiaBanP.getText().isEmpty()
                || txtSoLuongP.getText().isEmpty()) {

            sendMess("Yeu cau nhap du thong tin.");

        } else {
            try {
                DiaPhim dp = new DiaPhim(txtMaSanPhamP.getText(),
                        txtTenSanPhamP.getText(),
                        Integer.parseInt(txtGiaMuaP.getText()),
                        Integer.parseInt(txtGiaBanP.getText()),
                        Integer.parseInt(txtSoLuongP.getText()),
                        txtDaoDien.getText(),
                        txtTheLoaiP.getText());
                QuanLy.themSanPham(dp);
                sendMess("Them thanh cong.");
                returnState = true;
                dispose();
            } catch (Exception ex) {
                sendMess("Thong tin khong hop le.");
            }
        }
    }//GEN-LAST:event_btnThemPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDiaPhimUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDiaPhimUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDiaPhimUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDiaPhimUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemDiaPhimUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDaoDien;
    private javax.swing.JTextField txtGiaBanP;
    private javax.swing.JTextField txtGiaMuaP;
    private javax.swing.JTextField txtMaSanPhamP;
    private javax.swing.JTextField txtSoLuongP;
    private javax.swing.JTextField txtTenSanPhamP;
    private javax.swing.JTextField txtTheLoaiP;
    // End of variables declaration//GEN-END:variables
}
