/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom5.ui;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nhom5.model.CuaHang;
import nhom5.model.HoaDonLuong;
import nhom5.model.NhanVienBanHang;
import nhom5.model.QuanLy;
import nhom5.util.ClonedNhanVien;
import nhom5.util.TienIch;

/**
 *
 * @author Hoai Nguyen
 */
public class TraLuongUI extends javax.swing.JDialog {

    private DefaultTableModel dtm = new DefaultTableModel();
    public boolean returnState;

    /**
     * Creates new form TraLuongUI
     */
    public TraLuongUI() {
        initComponents();
        setValueToModelTable();
    }

    public TraLuongUI(JFrame parent, String title, boolean modal) {
        super(parent, title, modal);
        returnState = false;
        initComponents();
        dtm = (DefaultTableModel) tbTraLuong.getModel();
        setValueToModelTable();
        showWindow();
    }

    private void showWindow() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void setValueToModelTable() {
        int tongChi = 0;
        for (NhanVienBanHang i : CuaHang.getDsNhanVien().values()) {
            Object[] rowData = {i.getTen(), i.getMa(), i.getGioTichLuy(), i.getLuongCoBan(), i.getGioTichLuy() * i.getLuongCoBan()};
            tongChi += i.getGioTichLuy() * i.getLuongCoBan();
            dtm.addRow(rowData);
        }
        txtTongChi.setText(tongChi + "");
    }

    public void clearTable() {
        dtm.setRowCount(0);
    }

    public void sendMess(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTraLuong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTongChi = new javax.swing.JTextField();
        btnTraLuong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbTraLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên", "Mã nhân viên", "Số giờ", "Lương cơ bản", "Tổng lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTraLuong);

        jLabel1.setText("Tổng chi:");

        txtTongChi.setEditable(false);

        btnTraLuong.setText("Trả lương");
        btnTraLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)
                                .addComponent(txtTongChi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTraLuong, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTongChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnTraLuong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraLuongActionPerformed

        // Kiem tra xem co nhan vien nao con active khong, neu con, tra luong that bai
        for (NhanVienBanHang nv : CuaHang.getDsNhanVien().values()) {
            if (nv.isActive()) {
                sendMess("Con nhan vien dang hoat dong, tra luong that bai");
                return;
            }
        }

        HoaDonLuong hdl = new HoaDonLuong(TienIch.sinhMaHDL(), new Date());

        for (NhanVienBanHang nv : CuaHang.getDsNhanVien().values()) {

            // Sao chep nhan vien vao bang luong
            ClonedNhanVien clone = new ClonedNhanVien(nv);
            hdl.themNV(clone);

            // Cap nhat lai nhan vien
            nv.setGioTichLuy(0);
        }

        QuanLy.themBangLuong(hdl);

        sendMess("Trả lương thành công");
        returnState = true;
        dispose();
    }//GEN-LAST:event_btnTraLuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraLuongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraLuongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraLuongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraLuongUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraLuongUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTraLuong;
    private javax.swing.JTextField txtTongChi;
    // End of variables declaration//GEN-END:variables
}
